# Kubernetes Dashboard
kind: Service
apiVersion: v1
metadata:
  labels:
    app: kong
    release: kubernetes-dashboard
  name: kubernetes-dashboard-kong-proxy
  namespace: kubernetes-dashboard
spec:
  type: NodePort
  ports:
    - nodePort: 30501
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app.kubernetes.io/name: kong
    app.kubernetes.io/instance: kubernetes-dashboard
---
# Prometheus
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-operated
  name: prometheus-operated-np
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - nodePort: 30502
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus
---
# Grafana
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: my-grafana
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - nodePort: 30503
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/name: grafana